---
title: "Biorentention plots"
author: "Dave Costello"
date: "5/10/2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

logaxis = function(minlog,maxlog,side){
  pow <- seq(minlog,maxlog,by=1)
  ticksat <- as.vector(sapply(pow, function(p) (1:10)*10^p))
  axis(side, 10^pow,las=1)
  axis(side, ticksat, labels=NA, tcl=-0.25, lwd=0, lwd.ticks=1)
}

library(lme4)
```



#Data import
```{r survey data}
soilchem <- read.csv(file="soil_metal_NEW.csv")
soilchem$Cell_no <- factor(soilchem$Cell_no)
summary(soilchem)

#Outliers
soilchem[soilchem$Sample=="30a",'Zn'] <- NA
soilchem[soilchem$Sample=="12a",'Cu'] <- NA

cell <- read.csv(file="cell_data_NEW.csv")
cell$Location_name <- as.character(cell$Location_name)
summary(cell)

#Merge both datasets
fullsoil <- merge(soilchem,cell[,c(2:10)],by="Cell_no")
summary(fullsoil)
```


```{r leach data}
leach <- read.csv(file="leach.csv")

#Outliers
leach$Cu_conc[leach$Cu_conc>200] <- NA

#Removal rates
leach$Curemove <- with(leach,(Cu_in_meas-Cu_conc)/Cu_in_meas) #Calculate % removal 
leach$Curemove[leach$Curemove<0] <-0 #Set all negative "removals" (i.e., soils added Cu) to zero
leach$Znremove <- with(leach,(Zn_in_meas-Zn_conc)/Zn_in_meas) #Calculate % removal 
leach$Znremove[leach$Znremove<0] <-0 #Set all negative "removals" (i.e., soils added Zn) to zero
leach$Pbremove <- with(leach,(Pb_in_meas-Pb_conc)/Pb_in_meas) #Calculate % removal 

#Cell characteristics (from survey analysis)

cell <- read.csv(file="cell_data_NEW.csv")
cell$Location_name <- as.character(cell$Location_name)

soilchem <- read.csv(file="soil_metal_NEW.csv")
cellOM <- aggregate(soilchem[,c('OM','BD')],by=list(soilchem$Cell_no),median,na.rm=T)

newleach <- merge(leach,cell[,2:13],by="Cell_no",all.x=T,all.y=F)
newleach <- merge(newleach,cellOM[,1:2],by.x="Cell_no",by.y="Group.1",all.x=T,all.y=F)

#Subsets of the different metal treatments
leachH <- subset(newleach,newleach$Metal=="High")
leachL <- subset(newleach,newleach$Metal=="Low")
leachN <- subset(newleach,newleach$Metal=="No")
```

```{r salty leach data}
saltleach <- read.csv(file="saltleach.csv")
saltleach$Cell_no <- factor(saltleach$Cell_no) 
```


###Bioretention cell size
```{r cell v. drain size}
pdf(file="./Figures/cellsize.pdf",height=4,width=4)
par(pin=c(2.5,2.5),mai=c(1,1,0.5,0.5))
plot(Cell_area~Drain_area,data=cell,log="xy",ylim=c(10,10000),xlim=c(100,10000),xaxt="n",yaxt="n",
     xlab=expression("Drainage basin area (m"^2*")"),ylab=expression("Bioretention cell area (m"^2*")"),
     cex=1.3,pch=c(5,19)[Retrofit])
logaxis(2,4,1)
logaxis(1,4,2)

#Practicioner benchmarks
abline(a=log10(1/20),1,lwd=2,lty=3) #Ideal size of cell 5-10% the size of drain area
abline(a=log10(1/10),1,lwd=2,lty=3) 
text(14000,220,"5%",pos=2)
text(14000,1200,"10%",pos=2)

#Our data
cdmod <- lm(log10(Cell_area)~log10(Drain_area),data=cell[cell$Drain_area!=0,])
abline(cdmod,col="red")
text(14000,4000,"29%",pos=2,col="red")


legend("topleft",legend=c("New build","Retrofit"),pch=c(5,19),pt.cex=1.3,cex=0.8)

points(100,345,pch=19,cex=1.3,col="grey75") #Cell with no drainage area

dev.off()
```

###Soil metals through time
```{r metal through time}
fullsoil$offAge <- ifelse(fullsoil$Depth=="0 to 10",fullsoil$Age+0.1,fullsoil$Age-0.1)
Cumod <- lmer(log10(Cu)~Age*Depth+log10(OM)+(1|Cell_no),data=fullsoil,REML=F)
Pbmod <- lmer(log10(Pb)~Age+Depth+log10(OM)+log10(OM):Age+(1|Cell_no),data=fullsoil,REML=F)
Znmod <- lmer(log10(Zn)~Age+Depth+log10(OM)+(1|Cell_no),data=fullsoil,REML=F)

xAge <- seq(0,7,length=50)
yCudep <- predict(Cumod,newdata=list(Age=xAge,Depth=rep("10 to 20",length(xAge)),
                                     OM=rep(median(fullsoil$OM,na.rm=T),length(xAge))),re.form=~0)
yCush <- predict(Cumod,newdata=list(Age=xAge,Depth=rep("0 to 10",length(xAge)),
                                     OM=rep(median(fullsoil$OM,na.rm=T),length(xAge))),re.form=~0)

yPbdep <- predict(Pbmod,newdata=list(Age=xAge,Depth=rep("10 to 20",length(xAge)),
                                     OM=rep(median(fullsoil$OM,na.rm=T),length(xAge))),re.form=~0)
yPbsh <- predict(Pbmod,newdata=list(Age=xAge,Depth=rep("0 to 10",length(xAge)),
                                     OM=rep(median(fullsoil$OM,na.rm=T),length(xAge))),re.form=~0)

yZnS <- predict(Znmod,newdata=list(Age=xAge,Depth=rep("0 to 10",length(xAge)),
                                   OM=rep(median(fullsoil$OM,na.rm=T),length(xAge))),re.form=~0)
yZnD <- predict(Znmod,newdata=list(Age=xAge,Depth=rep("10 to 20",length(xAge)),
                                   OM=rep(median(fullsoil$OM,na.rm=T),length(xAge))),re.form=~0)

  
pdf(file="./Figures/cellmetal.pdf",height=5,width=3)

par(mfrow=c(3,1),oma=c(3,5,0,1),mar=c(0,0,2,0))
plot(Cu~offAge,data=fullsoil,log="y",yaxt="n",ylim=c(5,1000),xaxt="n",
     col=c("black","red")[Depth],pch=c(1,15)[Depth],cex=1.1)
lines(xAge,10^yCudep,col="red")
lines(xAge,10^yCush,col="black")
logaxis(0,3,2)
axis(1,labels=F)
mtext(expression("Soil Cu (mg kg"^-1*")"),2,line=3,cex=0.8)
mtext("a",2,line=-1,at=800,las=1)

legend("topright",legend=c("Surface (0-10 cm)","Deep (10-20 cm)"),pch=c(1,15),
       col=c("black","red"),lty=1)

par(mar=c(1,0,1,0))
plot(Pb~offAge,data=fullsoil,log="y",yaxt="n",ylim=c(5,1000),xaxt="n",
     col=c("black","red")[Depth],pch=c(1,15)[Depth],cex=1.1)
logaxis(1,3,2)
axis(1,labels=F)
mtext(expression("Soil Pb (mg kg"^-1*")"),2,line=3,cex=0.8)
mtext("b",2,line=-1,at=800,las=1)
lines(xAge,10^yPbdep,col="red")
lines(xAge,10^yPbsh,col="black")

par(mar=c(2,0,0,0))
plot(Zn~offAge,data=fullsoil,log="y",yaxt="n",ylim=c(10,1000),
     col=c("black","red")[Depth],pch=c(1,15)[Depth],cex=1.1)
logaxis(1,3,2)
mtext(expression("Soil Zn (mg kg"^-1*")"),2,line=3,cex=0.8)
mtext("Age (yr)",1,line=3,cex=0.8)
mtext("c",2,line=-1,at=800,las=1)
lines(xAge,10^yZnD,col="red")
lines(xAge,10^yZnS,col="black")


dev.off()
```

###Metal removal 
```{r removal efficiency}
pdf(file="./Figures/metalleach.pdf",height=5.25,width=3)

par(mfrow=c(2,3),oma=c(1,5,1,1),mar=c(0.25,0.25,4,0.25),xaxt="n")
plot.new()
abline(h=max(leachH$Curemove,na.rm=T)+0.005,col="red")
boxplot(Curemove~Retrofit,data=leachH,col=c("white","grey50"),las=1,add=T,at=c(0.25,0.75),boxwex=0.4)
mtext("Cu",3,0,cex=0.8)
mtext("Proportion removed",2,3)
legend("bottomleft",legend=c("New build","Retrofit"),fill=c("white","grey50"),cex=0.8,bty="n")
plot.new()
abline(h=max(leachH$Pbremove,na.rm=T)+0.01,col="red")
plot(Pbremove~Retrofit,data=leachH,yaxt="n",col=c("white","grey50"),add=T,at=c(0.25,0.75),boxwex=0.4)
mtext("Pb",3,0,cex=0.8)
mtext("Highly polluted",3,2)
plot.new()
abline(h=max(leachH$Znremove,na.rm=T)+0.005,col="red")
plot(Znremove~Retrofit,data=leachH,yaxt="n",col=c("white","grey50"),add=T,at=c(0.25,0.75),boxwex=0.4)
mtext("Zn",3,0,cex=0.8)

par(mar=c(0,0.25,4.25,0.25))
plot.new()
abline(h=max(leachL$Curemove,na.rm=T)+0.005,col="red")
boxplot(Curemove~Retrofit,data=leachL,col=c("white","grey50"),las=1,add=T,at=c(0.25,0.75),boxwex=0.4)
mtext("Proportion removed",2,3)
mtext("Cu",3,0,cex=0.8)
plot.new()
abline(h=max(leachL$Pbremove,na.rm=T)+0.01,col="red")
plot(Pbremove~Retrofit,data=leachL,yaxt="n",col=c("white","grey50"),add=T,at=c(0.25,0.75),boxwex=0.4)
mtext("Pb",3,0,cex=0.8)
mtext("Moderately polluted",3,2)
plot.new()
abline(h=max(leachL$Znremove,na.rm=T)+0.005,col="red")
plot(Znremove~Retrofit,data=leachL,yaxt="n",col=c("white","grey50"),add=T,at=c(0.25,0.75),boxwex=0.4)
mtext("Zn",3,0,cex=0.8)

dev.off()
```

###Zn leaching from clean stormwater
```{r}
library(lme4)
ZnN <- lmer(log10(Zn_conc)~log10(OM)+(1|Cell_no),data=leachN,REML=F)
newOM <- seq(4,16,by=0.1)
predZn <- 10^(fixef(ZnN)[1]+fixef(ZnN)[2]*log10(newOM))

pdf(file="./Figures/Zncleanleach.pdf",height=4,width=4)
par(pin=c(2.5,2.5),mai=c(1,1,0.5,0.5))
plot(Zn_conc~OM,data=leachN,log="y",yaxt="n",ylim=c(1,1000),xlim=c(4,16),
     ylab="Zn in leachate (ug/L)",xlab="Soil organic matter (%)")
logaxis(0,3,2)
points(predZn~newOM,type="l",col="red")
dev.off()
```

###Salty comparison leaching
```{r}
pdf(file="./Figures/salty.pdf",height=5,width=3)

par(mfrow=c(3,1),oma=c(3,7,0,1),mar=c(0,0,2,0))

boxplot(Cu_conc~Salt*Metal,data=saltleach,las=2,log="y",ylim=c(1,1000),yaxt="n",xaxt="n",
        xlim=c(0.5,7.5),at=c(1,2,3.5,4.5,6,7),
        col=c("lightblue","white"),border=c("lightblue","black"))
logaxis(0,3,2)
mtext("Cu (ug/L)",side=2,line=3,cex=0.6)
par(mar=c(0.5,0,0.5,0))
boxplot(Pb_conc~Salt*Metal,data=saltleach,las=2,ylim=c(1,1000),yaxt="n",xaxt="n",log="y",
        xlim=c(0.5,7.5),at=c(1,2,3.5,4.5,6,7),
        col=c("lightblue","white"),border=c("lightblue","black"))
logaxis(0,3,2)
mtext("Pb (ug/L)",side=2,line=3,cex=0.6)
mtext("Metal concentration in leachate",side=2,line=4.5,cex=0.8)
legend("topright",c("High salt","Low salt"),fill=c("lightblue","white"))
par(mar=c(2,0,0,0))
boxplot(Zn_conc~Salt*Metal,data=saltleach,las=2,ylim=c(1,1000),yaxt="n",xaxt="n",log="y",
        xlim=c(0.5,7.5),at=c(1,2,3.5,4.5,6,7),
        col=c("lightblue","white"),border=c("lightblue","black"))
logaxis(0,3,2)
mtext("Zn (ug/L)",side=2,line=3,cex=0.6)
mtext(c("High","Low","Clean"),at=c(1.5,4,6.5),side=1,line=0.5,cex=0.6)
mtext("Stormwater metal",side=1,line=2,cex=0.8)

dev.off()
```

